-- Talleres Ruiz · tablas del taller.
-- Los trabajos, piezas, observaciones e historial de cada orden van dentro de la
-- propia orden (jsonb): cada cambio en una orden se guarda de una vez (todo o
-- nada) y la columna "version" evita que dos personas se pisen los cambios.

create sequence public.orden_numero start with 1000;
create sequence public.visitante_web start with 1;

create table public.personas (
  id text primary key check (id ~ '^[a-z]{2,30}$'),
  nombre text not null,
  nombre_completo text not null,
  rol text not null check (rol in ('dueno', 'recepcion', 'mecanico')),
  rol_etiqueta text not null
);
comment on table public.personas is 'Personas del taller. Su acceso está en Authentication (app_metadata.persona).';

create table public.clientes (
  id text primary key check (length(id) between 1 and 60),
  nombre text not null check (length(btrim(nombre)) between 1 and 200),
  nombre_corto text not null check (length(nombre_corto) between 1 and 200),
  contacto text check (length(contacto) <= 200),
  telefono text not null default '' check (length(telefono) <= 60),
  email text not null default '' check (length(email) <= 200),
  desde int not null check (desde between 1900 and 2200),
  creado timestamptz not null default now()
);

create table public.coches (
  id text primary key check (length(id) between 1 and 60),
  cliente_id text not null references public.clientes (id) on update cascade on delete restrict,
  matricula text not null check (length(btrim(matricula)) between 4 and 20),
  matricula_clave text generated always as (upper(regexp_replace(matricula, '[\s-]', '', 'g'))) stored,
  modelo text not null check (length(btrim(modelo)) between 1 and 200),
  anio int check (anio between 1950 and 2200),
  combustible text not null default 'Gasolina' check (length(combustible) <= 40),
  creado timestamptz not null default now(),
  constraint coches_matricula_unica unique (matricula_clave)
);
create index coches_cliente_idx on public.coches (cliente_id);

create table public.tarifa (
  id text primary key check (length(id) between 1 and 60),
  categoria text not null check (length(btrim(categoria)) between 1 and 100),
  nombre text not null check (length(btrim(nombre)) between 1 and 200),
  tiempo text not null default '' check (length(tiempo) <= 60),
  precio numeric(10, 2) not null check (precio between 0 and 100000),
  por_unidad boolean not null default false,
  posicion int generated by default as identity
);

create table public.ordenes (
  id text primary key default ('OT-' || nextval('public.orden_numero')),
  coche_id text not null references public.coches (id) on update cascade on delete restrict,
  estado text not null default 'recibido'
    check (estado in ('recibido', 'diagnostico', 'pieza', 'reparacion', 'listo', 'entregado')),
  km int not null check (km between 0 and 3000000),
  mecanico_id text not null references public.personas (id),
  entrada timestamptz not null default now(),
  cierre timestamptz,
  motivo text not null check (length(btrim(motivo)) between 1 and 2000),
  trabajos jsonb not null default '[]' check (jsonb_typeof(trabajos) = 'array'),
  piezas jsonb not null default '[]' check (jsonb_typeof(piezas) = 'array'),
  observaciones jsonb not null default '[]' check (jsonb_typeof(observaciones) = 'array'),
  historial jsonb not null default '[]' check (jsonb_typeof(historial) = 'array'),
  ultima_ia jsonb check (ultima_ia is null or jsonb_typeof(ultima_ia) = 'object'),
  informes jsonb not null default '{}' check (jsonb_typeof(informes) = 'object'),
  version int not null default 1,
  constraint ordenes_cierre_coherente check ((estado = 'entregado') = (cierre is not null))
);
-- Un coche solo puede tener una orden abierta a la vez.
create unique index ordenes_una_abierta_por_coche on public.ordenes (coche_id) where estado <> 'entregado';
create index ordenes_coche_idx on public.ordenes (coche_id);
create index ordenes_mecanico_abiertas_idx on public.ordenes (mecanico_id) where estado <> 'entregado';
create index ordenes_mecanico_idx on public.ordenes (mecanico_id);

create table public.conversaciones (
  id text primary key check (length(id) between 1 and 60),
  cliente_id text references public.clientes (id) on update cascade on delete set null,
  nombre text not null default '' check (length(nombre) <= 200),
  canal text not null check (canal in ('WhatsApp', 'Email', 'Web')),
  contacto text check (length(contacto) <= 200),
  modo text not null default 'ia' check (modo in ('ia', 'persona')),
  necesita_persona boolean not null default false,
  motivo text check (length(motivo) <= 300),
  ia_pensando_desde timestamptz,
  actualizada timestamptz not null default now(),
  creada timestamptz not null default now()
);
create index conversaciones_cliente_idx on public.conversaciones (cliente_id);
create index conversaciones_bandeja_idx on public.conversaciones (necesita_persona desc, actualizada desc);

create table public.mensajes (
  n bigint generated always as identity,
  id text primary key check (length(id) between 1 and 60),
  conversacion_id text not null references public.conversaciones (id) on update cascade on delete cascade,
  de text not null check (de in ('cliente', 'ia', 'persona')),
  texto text not null check (length(texto) between 1 and 4000),
  cuando timestamptz not null default now(),
  autor text check (length(autor) <= 100)
);
create index mensajes_conversacion_idx on public.mensajes (conversacion_id, n);

create table public.citas (
  id text primary key check (length(id) between 1 and 60),
  fecha date not null,
  hora text not null check (hora ~ '^\d{2}:\d{2}$'),
  nombre text not null check (length(btrim(nombre)) between 1 and 200),
  telefono text not null default '' check (length(telefono) <= 60),
  matricula text not null check (length(btrim(matricula)) between 1 and 20),
  coche text not null default '—' check (length(coche) <= 200),
  motivo text not null default 'Sin especificar' check (length(motivo) <= 2000),
  cliente_id text references public.clientes (id) on update cascade on delete set null,
  orden_id text references public.ordenes (id) on update cascade on delete set null,
  conversacion_id text references public.conversaciones (id) on update cascade on delete set null,
  origen text not null check (origen in ('taller', 'ia')),
  creada timestamptz not null default now(),
  -- Un hueco, una cita (aunque dos personas reserven a la vez).
  constraint citas_hueco_unico unique (fecha, hora)
);
create index citas_cliente_idx on public.citas (cliente_id);
create index citas_orden_idx on public.citas (orden_id);
create index citas_conversacion_idx on public.citas (conversacion_id);
